### ISSUE TITLE
Cluster Classification

### ISSUE THREAD

**Issue by jjeamin** [warmspringwinds/segmentation_in_style#7]
Thanks for good work.

I read the paper. 

In the paper, there is a paragraph on Cluster Classification.

But I can't find it in the repo.

Where can I find it?

**Comment by warmspringwinds** [comment]
Hi,

We will add it shortly -- this part was recently added to the paper compared to the first draft.

**Comment by jjeamin** [comment]
Thank you. 

Looking forward to good work.
